# Домены
mmm-tasty.ru:
  name: ммм...тейсти

m.mmm-tasty.ru:
  name: ммм...тейсти
  mobile: true
  users: inline

tlogs.ru:
  name: tlogs.ru
  users: inline
  logo: logos/tlogs.png
  
localhost:
  users: inline
  url: http://localhost