# Environments
development:
  adapter: mysql
  database: tlogs_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: tlogs_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: tlogs_production
  username: root
  password: 
  host: localhost
