# Список доменов, флеш с которых можно размещать.
# Сделан специально, чтобы запретить постинги, например, игр и разной произвольной чепухи
---
- lookatme.ru
- youtube.com
- rutube.com
- rutube.ru
- vimeo.com
- rutube.ru
- gametrailers.com
- facecontrol.tv
- myspace.com 
- advancedmusic.com
- media.imeem.com
- russia-advancedmusic.com
- divshare.com
- miller-russia.com
- brightcove.com
- greenlabelsound.com
- imeem.com
- wired.com
- robotocom.net
- facebook.com
- flv-mp3.com
- muzicons.com
- dailymotion.com
- last.fm
- lastfm.ru
- smotri.com
- uppod.ru
- kremlin.ru
- ustream.tv
- issuu.com
- prostopleer.com
- soundcloud.com
- vkontakte.ru
- youtube.ru
- google.com
- yandex.ru
- mail.ru
- spotify.com
- now.ru
- snob.ru
- ivi.ru
- openspace.ru
- break.com
- zvooq.ru
- kinopoisk.ru