# Не забывайте не писать .js в конце имен файлов и перезагружать сервер

---
# Main
application:
- prototype.min
- effects.min
- dragdrop.min
- audio-player.min
- swfobject.min
- fancyzoom.min
- fancyzoomhtml.min
- fixpng
- error-messages-on
- openid
- google-analytics
- blink
- application