# Не забывайте не писать .js в конце имен файлов и перезагружать сервер

---
# Main
application:
# core libraries
- prototype.min
- effects.min
- dragdrop.min
- jquery-1.5.1.min
# jquery setup & plugins
- jquery.noconflict
- jquery.hotkeys
- jquery.autoresize.min
- jquery.infinitescroll.min
# - jquery.easing-1.3.pack
- jquery.fancybox-1.3.4.pack
- jquery.timeago
- jquery.timeago.ru
- jquery.popupWindow
- slides.min.jquery
- slides.configuration
# flash: swfobject & swfupload
- swfobject.min
- swfupload.min
# - swfupload.cookies.min
- swfupload.speed.min
# application code
- hotkeys
- uploader
- button
- autoresize
- audio-player.min
# - fancyzoom.min
# - fancyzoomhtml.min
- fixpng
- toggle-flash
- error-messages-on
- openid
- google-analytics
- blink
- application

mobile:
- jquery-1.6.1.min
- mobile
# - jquery.mobile-1.0b1.min
- jquery.timeago
- jquery.timeago.ru
- google-analytics

soundmanager:
- soundmanager2
- egych-player
# - page-player