# Не забывайте не писать .js в конце имен файлов и перезагружать сервер

---
# Main
application:
# core libraries
- prototype.min
- effects.min
- dragdrop.min
- jquery-1.5.1.min
# jquery setup & plugins
- jquery.noconflict
- jquery.hotkeys
- jquery.autoresize.min
- jquery.infinitescroll.min
- jquery.fancybox-1.3.4.pack
# flash: swfobject & swfupload
- swfobject.min
- swfupload.min
# - swfupload.cookies.min
- swfupload.speed.min
# application code
- hotkeys
- uploader
- button
- autoresize
- audio-player.min
# - fancyzoom.min
# - fancyzoomhtml.min
- fixpng
- toggle-flash
- error-messages-on
- openid
- google-analytics
- blink
- application