---
billing:
  # this is how much we charge for a single day of premium
  daily_rate: 2.33333333

  smsonline:
    login: user
    password: password
    prices: tmp/smsonline.xml                 # this is used by script/fetch_smsonline_prices script
    countries:
      - ru
      - ua
      - by
      - kz
      - md
    numbers:
      ru:
        - 6365
        - 1212
        - 8404
      ua:
        - 6365
        - 8385
        - 9395
      by:
        - 2090
        - 1315
        - 9395
      kz:
        - 6365
        - 9333
        - 9395
      md:
        - 7375
        - 8926
        - 8404
    duration:
      ru:
        6365: 29
        1212: 59
        8404: 99
      ua:
        6365: 29
        8385: 59
        9395: 99
      by:
        2090: 29
        1315: 59
        9395: 99
      kz:
        6365: 29
        9333: 59
        9395: 99
      md:
        7375: 29
        8926: 59
        8404: 99
    servers:
      - 83.137.50.31
      - 85.192.45.22
      - 194.67.81.38
      - 95.163.74.6
    key: xxx                                  # your sms online sign key (used for signing API requests)
  qiwi:
    login: 123456
    password: password
  robox:
    login: your-robox-login
    password1: merch-pass-1
    password2: merch-pass-2