---
billing:
  smsonline:
    login: user
    password: password
    prices: tmp/smsonline.xml                 # this is used by script/fetch_smsonline_prices script
    countries:
      - ru
      - ua
      - by
      - kz
      - md
    numbers:                                  # array of allowed sms numbers
      ru:
        - 6365
        - 1212
        - 8404
      ua:
        - 1315
        - 9395
      by:
        - 2090
        - 1315
        - 9395
    duration:
      ru:
        6365: 29
        1212: 59
        8404: 99
      ua:
        1315: 29
        9395: 99
      by:
        2090: 29
        1315: 59
        9395: 99
    servers:
      - 83.137.50.31
      - 85.192.45.22
      - 194.67.81.38
      - 95.163.74.6
    key: xxx                                  # your sms online sign key (used for signing API requests)
  qiwi:
    login: 123456
    password: password