# Не забывайте не писать .css в конце имен файлов и перезагружать сервер

---
# Главные стили
application:
  default: application
  ie: application.ie
  mobile: mobile

# Light layout
light:
  default: light