---
sets:
  -
    - url:    http://surfingbird.ru/surf/kL-2b8d8
      title:  Необычный фэшн-фотограф Габриэль Джуссан

    - url:    http://surfingbird.ru/surf/jHf8cc06
      title:  Самые няшные толстовки ever

    - url:    http://surfingbird.ru/surf/j5Y97781
      title:  Короткометражка о любви от финского режиссера

    - url:    http://surfingbird.ru/surf/gCE3560d
      title:  Рецепты особенно красивых блюд

    - url:    http://surfingbird.ru/surf/k4rB5005
      title:  Невероятные оптические иллюзии

    - url:    http://surfingbird.ru/surf/eCd7179 
      title:  Самый модный и крутой блог о дизайне

    - url:    http://surfingbird.ru/surf/klc0691d
      title:  Глаза решают. Веселый стрит-арт.

    - url:    http://surfingbird.ru/surf/ew229C3 
      title:  Арт-флэш журнал BigMag

  -
    - url:    http://surfingbird.ru/surf/eFBB70a   
      title:  Одно слово — ваниль!

    - url:    http://surfingbird.ru/surf/lo928DB0  
      title:  Вельш-корги или самые милые псы на свете

    - url:    http://surfingbird.ru/surf/eIb9EC2   
      title:  Современная культура в проекте «Чубакка»

    - url:    http://surfingbird.ru/surf/kLE3E8A4  
      title:  Дизайнер и видеомэйкер Люси МакРей

    - url:    http://surfingbird.ru/surf/kLk2E455  
      title:  Модные незнакомцы на улицах США и Австралии

    - url:    http://picturesthatlooklikethis.com/ 
      title: "Все, что окружает фотографа Ноа Калина"

    - url:    http://surfingbird.ru/surf/eH2e8cB   
      title: "Независимый проект о визуальном искусстве Moloko +"

    - url:    http://surfingbird.ru/surf/e.126F2   
      title: "My milk toof, фоторепортажи о приключениях молочных зубов"

  -
    - url:    http://surfingbird.ru/surf/mzqA745E
      title:  Онлайн журнал Yesway

    - url:    http://surfingbird.ru/surf/lk38F8aF
      title: "Нил Краг, фотограф и режиссер, симпатизирующий винтажу"

    - url:    http://surfingbird.ru/surf/mzh1c949
      title:  Лучшие российские иллюстраторы

    - url:    http://surfingbird.ru/surf/mkt83c1B
      title: "Sophie Van der Perr, 23-летняя любительница фотографировать"

    - url:    http://surfingbird.ru/surf/mkfB82Fa
      title: "8hate - об искусстве, музыке, фото и не только"

    - url:    http://surfingbird.ru/surf/cG.189a0
      title:  Интернет-магазин самых актуальных принтов

    - url:    http://surfingbird.ru/surf/kVyECCd2
      title: "Парни, которые танцуют везде"

    - url:    http://surfingbird.ru/surf/i7P7532F
      title: "Модная вышивка крестиком"

  -
    - title:  Красивый фотоблог «Говорящие пиксели»
      url:    http://surfingbird.ru/surf/kKq11A2b

    - title:  Иллюстратор и дизанер Йан Стивенсон
      url:    http://surfingbird.ru/surf/foJ51826

    - title:  Секреты кондитерского искусства от «Лис и оленей»
      url:    http://surfingbird.ru/surf/dP7c04De

    - title:  Невероятные иллюстрации Фабиана Сираоло
      url:    http://surfingbird.ru/surf/gKw1765E

    - title: "Полароиды и дизайн П. Х. Фицджеральда"
      url:    http://surfingbird.ru/surf/lk11183F

    - title: "Old-school как он есть: блог с фото родителей в молодости"
      url:    http://surfingbird.ru/surf/lkh2FF22      

    - title: "Молдова и мода, популярный фэшн-блог Дойны"
      url:    http://surfingbird.ru/surf/liq8bf5C

    - title:  Озеро Тахо и его окрестности
      url:    http://surfingbird.ru/surf/lOq16159
